"""Add campaign model

Revision ID: 1810356db0f0
Revises: 9960b25f98f7
Create Date: 2026-09-14 06:14:39.117935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1810356db0f0'
down_revision: Union[str, None] = '9960b25f98f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'SCHEDULED', 'COMPLETED', 'PAUSED', name='campaignstatus_enum'), nullable=False),
    sa.Column('eligibility_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('follow_up_window', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calling_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('calling_capacity', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_hospital_id'), 'campaigns', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_hospital_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
