"""Add validation and campaign patient

Revision ID: 23fa0740dfd4
Revises: 1810356db0f0
Create Date: 2026-09-14 06:48:29.024133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fa0740dfd4'
down_revision: Union[str, None] = '1810356db0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_patients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('eligibility_status', sa.String(length=50), nullable=False),
    sa.Column('eligibility_reason', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'patient_id', name='uq_campaign_patient')
    )
    op.create_index(op.f('ix_campaign_patients_campaign_id'), 'campaign_patients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_patients_patient_id'), 'campaign_patients', ['patient_id'], unique=False)
    campaignvalidationstatus_enum = sa.Enum('NOT_VALIDATED', 'VALID', 'INVALID', name='campaignvalidationstatus_enum')
    campaignvalidationstatus_enum.create(op.get_bind())
    op.add_column('campaigns', sa.Column('validation_status', campaignvalidationstatus_enum, nullable=False, server_default='NOT_VALIDATED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'validation_status')
    op.drop_index(op.f('ix_campaign_patients_patient_id'), table_name='campaign_patients')
    op.drop_index(op.f('ix_campaign_patients_campaign_id'), table_name='campaign_patients')
    op.drop_table('campaign_patients')
    # ### end Alembic commands ###
