"""Add outbound_calls table

Revision ID: 83de17350ea6
Revises: 8161cf356f97
Create Date: 2026-09-14 16:34:02.960078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83de17350ea6'
down_revision: Union[str, None] = '8161cf356f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('patient_reached', sa.Boolean(), nullable=False),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('symptoms_reported', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uncertainties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('callback_requested', sa.Boolean(), nullable=False),
    sa.Column('callback_time', sa.String(length=100), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_calls_campaign_id'), 'outbound_calls', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_outbound_calls_patient_id'), 'outbound_calls', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_calls_patient_id'), table_name='outbound_calls')
    op.drop_index(op.f('ix_outbound_calls_campaign_id'), table_name='outbound_calls')
    op.drop_table('outbound_calls')
    # ### end Alembic commands ###
