"""triage orchestration

Revision ID: 9d6336775b67
Revises: f0a51e6f0626
Create Date: 2026-09-14 20:00:17.994284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d6336775b67'
down_revision: Union[str, None] = 'f0a51e6f0626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('clinical_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('triage_results', sa.Column('consensus_level', sa.String(length=50), nullable=True))
    op.add_column('triage_results', sa.Column('consensus_method', sa.String(length=100), nullable=True))
    op.add_column('triage_results', sa.Column('disagreement_detected', sa.Boolean(), nullable=False))
    op.add_column('triage_results', sa.Column('ehr_action_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triage_results', 'ehr_action_status')
    op.drop_column('triage_results', 'disagreement_detected')
    op.drop_column('triage_results', 'consensus_method')
    op.drop_column('triage_results', 'consensus_level')
    op.drop_column('protocols', 'clinical_rules')
    # ### end Alembic commands ###
