"""add protocol to campaign

Revision ID: a6e89930bce2
Revises: 9d6336775b67
Create Date: 2026-09-14 20:09:33.132922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e89930bce2'
down_revision: Union[str, None] = '9d6336775b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('protocol_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'protocols', ['protocol_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'protocol_id')
    # ### end Alembic commands ###
