"""Add priority fields

Revision ID: cfd562b8f1ff
Revises: 23fa0740dfd4
Create Date: 2026-09-14 09:08:41.399644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfd562b8f1ff'
down_revision: Union[str, None] = '23fa0740dfd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_patients', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('campaign_patients', sa.Column('priority_level', sa.String(length=50), nullable=True))
    op.add_column('campaign_patients', sa.Column('priority_rank', sa.Integer(), nullable=True))
    op.add_column('campaign_patients', sa.Column('prioritized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaign_patients', sa.Column('priority_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_patients', 'priority_factors')
    op.drop_column('campaign_patients', 'prioritized_at')
    op.drop_column('campaign_patients', 'priority_rank')
    op.drop_column('campaign_patients', 'priority_level')
    op.drop_column('campaign_patients', 'priority_score')
    # ### end Alembic commands ###
