"""Add OutboundQueue

Revision ID: e35c34ec3717
Revises: cfd562b8f1ff
Create Date: 2026-09-14 10:28:00.249448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35c34ec3717'
down_revision: Union[str, None] = 'cfd562b8f1ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_level', sa.String(length=50), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='queueitemstatus_enum'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'patient_id', name='uq_outbound_queue_campaign_patient')
    )
    op.create_index(op.f('ix_outbound_queue_campaign_id'), 'outbound_queue', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_outbound_queue_hospital_id'), 'outbound_queue', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_outbound_queue_patient_id'), 'outbound_queue', ['patient_id'], unique=False)
    op.create_index(op.f('ix_outbound_queue_scheduled_at'), 'outbound_queue', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_outbound_queue_status'), 'outbound_queue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_queue_status'), table_name='outbound_queue')
    op.drop_index(op.f('ix_outbound_queue_scheduled_at'), table_name='outbound_queue')
    op.drop_index(op.f('ix_outbound_queue_patient_id'), table_name='outbound_queue')
    op.drop_index(op.f('ix_outbound_queue_hospital_id'), table_name='outbound_queue')
    op.drop_index(op.f('ix_outbound_queue_campaign_id'), table_name='outbound_queue')
    op.drop_table('outbound_queue')
    # ### end Alembic commands ###
