"""Add TriageResult

Revision ID: f0a51e6f0626
Revises: 0e532b23423e
Create Date: 2026-09-14 19:07:57.024429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0a51e6f0626'
down_revision: Union[str, None] = '0e532b23423e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('triage_level', sa.String(length=50), nullable=False),
    sa.Column('recommended_action', sa.String(length=100), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_protocol_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('agent_assessments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('protocol_name', sa.String(length=255), nullable=False),
    sa.Column('protocol_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['outbound_calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_results_call_id'), 'triage_results', ['call_id'], unique=False)
    op.create_index(op.f('ix_triage_results_campaign_id'), 'triage_results', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_triage_results_patient_id'), 'triage_results', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_results_patient_id'), table_name='triage_results')
    op.drop_index(op.f('ix_triage_results_campaign_id'), table_name='triage_results')
    op.drop_index(op.f('ix_triage_results_call_id'), table_name='triage_results')
    op.drop_table('triage_results')
    # ### end Alembic commands ###
